// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mezo/bridge/v1/bridge.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// max_erc20_tokens_mappings is the maximum number of distinct ERC20 tokens
	// mappings that can be supported in the bridge. The reason for this limit is
	// to not downgrade the bridge performance on the Mezo chain side too much.
	MaxErc20TokensMappings uint32 `protobuf:"varint,1,opt,name=max_erc20_tokens_mappings,json=maxErc20TokensMappings,proto3" json:"max_erc20_tokens_mappings,omitempty"`
	// btc_supply_assertion_enabled is a flag to enable/disable the assertion that
	// checks if the total BTC supply on the Mezo chain is equal to the difference
	// between the total BTC minted and burned by the bridge module.
	BtcSupplyAssertionEnabled bool `protobuf:"varint,2,opt,name=btc_supply_assertion_enabled,json=btcSupplyAssertionEnabled,proto3" json:"btc_supply_assertion_enabled,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7905948c23f4425c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxErc20TokensMappings() uint32 {
	if m != nil {
		return m.MaxErc20TokensMappings
	}
	return 0
}

func (m *Params) GetBtcSupplyAssertionEnabled() bool {
	if m != nil {
		return m.BtcSupplyAssertionEnabled
	}
	return false
}

// AssetsLockedEvent represents the event where inbound assets are locked in
// the Bitcoin bridge.
type AssetsLockedEvent struct {
	// sequence is the unique identifier of the event.
	Sequence cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=sequence,proto3,customtype=cosmossdk.io/math.Int" json:"sequence"`
	// recipient is the account address to receive the locked assets on Mezo,
	// in Bech32 format.
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// amount of assets locked, in 1e18 precision.
	Amount cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	// token is the hex-encoded EVM address of the bridged token.
	Token string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *AssetsLockedEvent) Reset()         { *m = AssetsLockedEvent{} }
func (m *AssetsLockedEvent) String() string { return proto.CompactTextString(m) }
func (*AssetsLockedEvent) ProtoMessage()    {}
func (*AssetsLockedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7905948c23f4425c, []int{1}
}
func (m *AssetsLockedEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetsLockedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetsLockedEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetsLockedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetsLockedEvent.Merge(m, src)
}
func (m *AssetsLockedEvent) XXX_Size() int {
	return m.Size()
}
func (m *AssetsLockedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetsLockedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AssetsLockedEvent proto.InternalMessageInfo

func (m *AssetsLockedEvent) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *AssetsLockedEvent) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// ERC20TokenMapping defines a mapping between an ERC20 token on the source chain
// and on the Mezo chain.
type ERC20TokenMapping struct {
	// source_token is the hex-encoded EVM address of the token on the source chain.
	SourceToken string `protobuf:"bytes,1,opt,name=source_token,json=sourceToken,proto3" json:"source_token,omitempty"`
	// mezo_token is the hex-encoded EVM address of the token on the Mezo chain.
	MezoToken string `protobuf:"bytes,2,opt,name=mezo_token,json=mezoToken,proto3" json:"mezo_token,omitempty"`
}

func (m *ERC20TokenMapping) Reset()         { *m = ERC20TokenMapping{} }
func (m *ERC20TokenMapping) String() string { return proto.CompactTextString(m) }
func (*ERC20TokenMapping) ProtoMessage()    {}
func (*ERC20TokenMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_7905948c23f4425c, []int{2}
}
func (m *ERC20TokenMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ERC20TokenMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ERC20TokenMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ERC20TokenMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERC20TokenMapping.Merge(m, src)
}
func (m *ERC20TokenMapping) XXX_Size() int {
	return m.Size()
}
func (m *ERC20TokenMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_ERC20TokenMapping.DiscardUnknown(m)
}

var xxx_messageInfo_ERC20TokenMapping proto.InternalMessageInfo

func (m *ERC20TokenMapping) GetSourceToken() string {
	if m != nil {
		return m.SourceToken
	}
	return ""
}

func (m *ERC20TokenMapping) GetMezoToken() string {
	if m != nil {
		return m.MezoToken
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "mezo.bridge.v1.Params")
	proto.RegisterType((*AssetsLockedEvent)(nil), "mezo.bridge.v1.AssetsLockedEvent")
	proto.RegisterType((*ERC20TokenMapping)(nil), "mezo.bridge.v1.ERC20TokenMapping")
}

func init() { proto.RegisterFile("mezo/bridge/v1/bridge.proto", fileDescriptor_7905948c23f4425c) }

var fileDescriptor_7905948c23f4425c = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0xae, 0xd3, 0x30,
	0x14, 0xc6, 0x63, 0xb8, 0x54, 0xb7, 0xe6, 0x8f, 0x74, 0xad, 0x0b, 0xca, 0x85, 0xdb, 0xb4, 0x74,
	0xea, 0x42, 0x42, 0x41, 0x0c, 0x65, 0x41, 0x14, 0x65, 0x40, 0x02, 0x09, 0x05, 0x58, 0x58, 0x22,
	0xc7, 0x39, 0x4a, 0xa3, 0xd6, 0x76, 0xb0, 0x9d, 0xaa, 0xe5, 0x11, 0x98, 0x18, 0x19, 0x79, 0x0d,
	0xde, 0xa0, 0x63, 0x47, 0xc4, 0x50, 0xa1, 0xf6, 0x45, 0x50, 0x1c, 0x17, 0xd6, 0xbb, 0x1d, 0x7f,
	0xdf, 0x4f, 0x47, 0x9f, 0xbe, 0x63, 0xfc, 0x80, 0xc3, 0x17, 0x19, 0x65, 0xaa, 0xcc, 0x0b, 0x88,
	0x96, 0x63, 0x37, 0x85, 0x95, 0x92, 0x46, 0x92, 0x3b, 0x8d, 0x19, 0x3a, 0x69, 0x39, 0xbe, 0x7f,
	0x5e, 0xc8, 0x42, 0x5a, 0x2b, 0x6a, 0xa6, 0x96, 0x1a, 0x7e, 0x45, 0xb8, 0xf3, 0x8e, 0x2a, 0xca,
	0x35, 0x99, 0xe0, 0x0b, 0x4e, 0x57, 0x29, 0x28, 0xf6, 0xe4, 0x71, 0x6a, 0xe4, 0x1c, 0x84, 0x4e,
	0x39, 0xad, 0xaa, 0x52, 0x14, 0xda, 0x47, 0x03, 0x34, 0xba, 0x9d, 0xdc, 0xe3, 0x74, 0x15, 0x37,
	0xfe, 0x07, 0x6b, 0xbf, 0x75, 0x2e, 0x79, 0x81, 0x2f, 0x33, 0xc3, 0x52, 0x5d, 0x57, 0xd5, 0x62,
	0x9d, 0x52, 0xad, 0x41, 0x99, 0x52, 0x8a, 0x14, 0x04, 0xcd, 0x16, 0x90, 0xfb, 0xd7, 0x06, 0x68,
	0x74, 0x9a, 0x5c, 0x64, 0x86, 0xbd, 0xb7, 0xc8, 0xcb, 0x23, 0x11, 0xb7, 0xc0, 0xf3, 0x93, 0xef,
	0x3f, 0xfa, 0xde, 0xf0, 0x27, 0xc2, 0x67, 0x8d, 0x65, 0xf4, 0x1b, 0xc9, 0xe6, 0x90, 0xc7, 0x4b,
	0x10, 0x86, 0x4c, 0xf0, 0xa9, 0x86, 0xcf, 0x35, 0x08, 0x06, 0x36, 0x46, 0x77, 0xda, 0xdb, 0xec,
	0xfa, 0xde, 0xef, 0x5d, 0xff, 0x2e, 0x93, 0x9a, 0x4b, 0xad, 0xf3, 0x79, 0x58, 0xca, 0x88, 0x53,
	0x33, 0x0b, 0x5f, 0x0b, 0x93, 0xfc, 0xc3, 0xc9, 0x25, 0xee, 0x2a, 0x60, 0x65, 0x55, 0x82, 0x30,
	0x36, 0x44, 0x37, 0xf9, 0x2f, 0x90, 0x67, 0xb8, 0x43, 0xb9, 0xac, 0x85, 0xf1, 0xaf, 0x5f, 0x65,
	0xad, 0x83, 0xc9, 0x39, 0xbe, 0x61, 0xdb, 0xf1, 0x4f, 0xec, 0xc2, 0xf6, 0x31, 0xfc, 0x88, 0xcf,
	0xe2, 0xe4, 0x95, 0x6b, 0xc6, 0x15, 0x43, 0x1e, 0xe2, 0x5b, 0x5a, 0xd6, 0x8a, 0x41, 0xdb, 0x67,
	0x1b, 0x3f, 0xb9, 0xd9, 0x6a, 0x96, 0x24, 0x3d, 0x8c, 0x9b, 0x43, 0x39, 0xc0, 0x65, 0x6c, 0x14,
	0x6b, 0x4f, 0xa7, 0x9b, 0x7d, 0x80, 0xb6, 0xfb, 0x00, 0xfd, 0xd9, 0x07, 0xe8, 0xdb, 0x21, 0xf0,
	0xb6, 0x87, 0xc0, 0xfb, 0x75, 0x08, 0xbc, 0x4f, 0xa3, 0xa2, 0x34, 0xb3, 0x3a, 0x0b, 0x99, 0xe4,
	0x51, 0xc3, 0x3f, 0x92, 0xaa, 0xb0, 0x43, 0x1e, 0xad, 0x8e, 0x7f, 0xc2, 0xac, 0x2b, 0xd0, 0x59,
	0xc7, 0x9e, 0xfa, 0xe9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x90, 0x61, 0x7e, 0x2f, 0x02,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BtcSupplyAssertionEnabled {
		i--
		if m.BtcSupplyAssertionEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.MaxErc20TokensMappings != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.MaxErc20TokensMappings))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AssetsLockedEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetsLockedEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetsLockedEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBridge(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.Sequence.Size()
		i -= size
		if _, err := m.Sequence.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBridge(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ERC20TokenMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ERC20TokenMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ERC20TokenMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MezoToken) > 0 {
		i -= len(m.MezoToken)
		copy(dAtA[i:], m.MezoToken)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.MezoToken)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SourceToken) > 0 {
		i -= len(m.SourceToken)
		copy(dAtA[i:], m.SourceToken)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.SourceToken)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBridge(dAtA []byte, offset int, v uint64) int {
	offset -= sovBridge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxErc20TokensMappings != 0 {
		n += 1 + sovBridge(uint64(m.MaxErc20TokensMappings))
	}
	if m.BtcSupplyAssertionEnabled {
		n += 2
	}
	return n
}

func (m *AssetsLockedEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Sequence.Size()
	n += 1 + l + sovBridge(uint64(l))
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovBridge(uint64(l))
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	return n
}

func (m *ERC20TokenMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourceToken)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	l = len(m.MezoToken)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	return n
}

func sovBridge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBridge(x uint64) (n int) {
	return sovBridge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxErc20TokensMappings", wireType)
			}
			m.MaxErc20TokensMappings = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxErc20TokensMappings |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcSupplyAssertionEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BtcSupplyAssertionEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBridge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AssetsLockedEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetsLockedEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetsLockedEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sequence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBridge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ERC20TokenMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ERC20TokenMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ERC20TokenMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MezoToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MezoToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBridge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBridge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBridge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBridge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBridge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBridge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBridge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBridge = fmt.Errorf("proto: unexpected end of group")
)
