// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mezo/bridge/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the bridge module's genesis state.
type GenesisState struct {
	// params defines all the parameters of related to bridge.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// assets_locked_sequence_tip is the current sequence tip for the AssetsLocked
	// events. The tip denotes the sequence number of the last event processed by
	// the x/bridge module.
	AssetsLockedSequenceTip cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=assets_locked_sequence_tip,json=assetsLockedSequenceTip,proto3,customtype=cosmossdk.io/math.Int" json:"assets_locked_sequence_tip"`
	// source_btc_token is the hex-encoded EVM address of the BTC token on the
	// source chain. AssetsLocked events carrying this token address are directly
	// mapped to the Mezo native denomination - BTC.
	SourceBtcToken string `protobuf:"bytes,3,opt,name=source_btc_token,json=sourceBtcToken,proto3" json:"source_btc_token,omitempty"`
	// erc20_tokens_mappings is the list of ERC20 token mappings supported by the
	// bridge.
	Erc20TokensMappings []*ERC20TokenMapping `protobuf:"bytes,4,rep,name=erc20_tokens_mappings,json=erc20TokensMappings,proto3" json:"erc20_tokens_mappings,omitempty"`
	// initial_btc_supply is the BTC supply minted by the network
	// at genesis, this is used only for development / testnet purpose
	// and should be left set to 0 in an production network.
	InitialBtcSupply cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=initial_btc_supply,json=initialBtcSupply,proto3,customtype=cosmossdk.io/math.Int" json:"initial_btc_supply"`
	// assets_unlocked_sequence_tip is the current sequence tip for the
	// AssetsUnlocked events. The tip denotes the sequence number of the last
	// event processed by the x/bridge module.
	AssetsUnlockedSequenceTip cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=assets_unlocked_sequence_tip,json=assetsUnlockedSequenceTip,proto3,customtype=cosmossdk.io/math.Int" json:"assets_unlocked_sequence_tip"`
	// assets_unlocked_events are all the AssetsUnlockedEvents processed
	// by the networks' bridge.
	AssetsUnlockedEvents []*AssetsUnlockedEvent `protobuf:"bytes,7,rep,name=assets_unlocked_events,json=assetsUnlockedEvents,proto3" json:"assets_unlocked_events,omitempty"`
	// bitcoin_chain_min_bridge_out_amount is the minimum amount required
	// for bridging out to the Bitcoin chain.
	BitcoinChainMinBridgeOutAmount cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=bitcoin_chain_min_bridge_out_amount,json=bitcoinChainMinBridgeOutAmount,proto3,customtype=cosmossdk.io/math.Int" json:"bitcoin_chain_min_bridge_out_amount"`
	// token_min_bridge_out_amounts is the list of minimum bridge out amounts
	// per token for the Bitcoin chain.
	TokenMinBridgeOutAmounts []*TokenMinBridgeOutAmount `protobuf:"bytes,9,rep,name=token_min_bridge_out_amounts,json=tokenMinBridgeOutAmounts,proto3" json:"token_min_bridge_out_amounts,omitempty"`
	Pauser                   []byte                     `protobuf:"bytes,10,opt,name=pauser,proto3" json:"pauser,omitempty"`
	LastOutflowReset         uint64                     `protobuf:"varint,11,opt,name=last_outflow_reset,json=lastOutflowReset,proto3" json:"last_outflow_reset,omitempty"`
	CurrentOutflowAmounts    []*CurrentOutflowAmount    `protobuf:"bytes,12,rep,name=current_outflow_amounts,json=currentOutflowAmounts,proto3" json:"current_outflow_amounts,omitempty"`
	CurrentOutflowLimits     []*CurrentOutflowLimit     `protobuf:"bytes,13,rep,name=current_outflow_limits,json=currentOutflowLimits,proto3" json:"current_outflow_limits,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9d1c622979efc, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetSourceBtcToken() string {
	if m != nil {
		return m.SourceBtcToken
	}
	return ""
}

func (m *GenesisState) GetErc20TokensMappings() []*ERC20TokenMapping {
	if m != nil {
		return m.Erc20TokensMappings
	}
	return nil
}

func (m *GenesisState) GetAssetsUnlockedEvents() []*AssetsUnlockedEvent {
	if m != nil {
		return m.AssetsUnlockedEvents
	}
	return nil
}

func (m *GenesisState) GetTokenMinBridgeOutAmounts() []*TokenMinBridgeOutAmount {
	if m != nil {
		return m.TokenMinBridgeOutAmounts
	}
	return nil
}

func (m *GenesisState) GetPauser() []byte {
	if m != nil {
		return m.Pauser
	}
	return nil
}

func (m *GenesisState) GetLastOutflowReset() uint64 {
	if m != nil {
		return m.LastOutflowReset
	}
	return 0
}

func (m *GenesisState) GetCurrentOutflowAmounts() []*CurrentOutflowAmount {
	if m != nil {
		return m.CurrentOutflowAmounts
	}
	return nil
}

func (m *GenesisState) GetCurrentOutflowLimits() []*CurrentOutflowLimit {
	if m != nil {
		return m.CurrentOutflowLimits
	}
	return nil
}

type CurrentOutflowAmount struct {
	Token  []byte                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Amount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *CurrentOutflowAmount) Reset()         { *m = CurrentOutflowAmount{} }
func (m *CurrentOutflowAmount) String() string { return proto.CompactTextString(m) }
func (*CurrentOutflowAmount) ProtoMessage()    {}
func (*CurrentOutflowAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9d1c622979efc, []int{1}
}
func (m *CurrentOutflowAmount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentOutflowAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentOutflowAmount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentOutflowAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentOutflowAmount.Merge(m, src)
}
func (m *CurrentOutflowAmount) XXX_Size() int {
	return m.Size()
}
func (m *CurrentOutflowAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentOutflowAmount.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentOutflowAmount proto.InternalMessageInfo

func (m *CurrentOutflowAmount) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type CurrentOutflowLimit struct {
	Token []byte                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Limit cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=limit,proto3,customtype=cosmossdk.io/math.Int" json:"limit"`
}

func (m *CurrentOutflowLimit) Reset()         { *m = CurrentOutflowLimit{} }
func (m *CurrentOutflowLimit) String() string { return proto.CompactTextString(m) }
func (*CurrentOutflowLimit) ProtoMessage()    {}
func (*CurrentOutflowLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9d1c622979efc, []int{2}
}
func (m *CurrentOutflowLimit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentOutflowLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentOutflowLimit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentOutflowLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentOutflowLimit.Merge(m, src)
}
func (m *CurrentOutflowLimit) XXX_Size() int {
	return m.Size()
}
func (m *CurrentOutflowLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentOutflowLimit.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentOutflowLimit proto.InternalMessageInfo

func (m *CurrentOutflowLimit) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

// TokenMinBridgeOutAmount defines the minimum bridge out amount for a specific
// token.
type TokenMinBridgeOutAmount struct {
	// token is the token address as bytes.
	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// amount is the minimum amount required for bridging out this specific token.
	Amount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *TokenMinBridgeOutAmount) Reset()         { *m = TokenMinBridgeOutAmount{} }
func (m *TokenMinBridgeOutAmount) String() string { return proto.CompactTextString(m) }
func (*TokenMinBridgeOutAmount) ProtoMessage()    {}
func (*TokenMinBridgeOutAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9d1c622979efc, []int{3}
}
func (m *TokenMinBridgeOutAmount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenMinBridgeOutAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenMinBridgeOutAmount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenMinBridgeOutAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMinBridgeOutAmount.Merge(m, src)
}
func (m *TokenMinBridgeOutAmount) XXX_Size() int {
	return m.Size()
}
func (m *TokenMinBridgeOutAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMinBridgeOutAmount.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMinBridgeOutAmount proto.InternalMessageInfo

func (m *TokenMinBridgeOutAmount) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "mezo.bridge.v1.GenesisState")
	proto.RegisterType((*CurrentOutflowAmount)(nil), "mezo.bridge.v1.CurrentOutflowAmount")
	proto.RegisterType((*CurrentOutflowLimit)(nil), "mezo.bridge.v1.CurrentOutflowLimit")
	proto.RegisterType((*TokenMinBridgeOutAmount)(nil), "mezo.bridge.v1.TokenMinBridgeOutAmount")
}

func init() { proto.RegisterFile("mezo/bridge/v1/genesis.proto", fileDescriptor_c6a9d1c622979efc) }

var fileDescriptor_c6a9d1c622979efc = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x4e, 0xdc, 0x3a,
	0x14, 0xc7, 0x27, 0x17, 0x18, 0x2e, 0x86, 0x8b, 0x90, 0x19, 0x20, 0x97, 0xcb, 0x0d, 0xd3, 0xa1,
	0x52, 0xb3, 0x68, 0x13, 0x18, 0xda, 0x07, 0x20, 0x08, 0x55, 0x55, 0x41, 0x54, 0x01, 0x16, 0x45,
	0x55, 0xd3, 0x8c, 0xc7, 0x04, 0x97, 0x89, 0x9d, 0xe6, 0x38, 0xb4, 0xf4, 0x29, 0xfa, 0x58, 0x2c,
	0x59, 0x56, 0x5d, 0xa0, 0x0a, 0x9e, 0xa3, 0x52, 0x65, 0x3b, 0xa8, 0x25, 0x04, 0x69, 0x16, 0xdd,
	0xc5, 0xe7, 0xfc, 0xcf, 0xef, 0x7c, 0xc5, 0x46, 0x4b, 0x29, 0xfd, 0x2c, 0xfc, 0x5e, 0xce, 0xfa,
	0x09, 0xf5, 0x4f, 0xd7, 0xfc, 0x84, 0x72, 0x0a, 0x0c, 0xbc, 0x2c, 0x17, 0x52, 0xe0, 0x69, 0xe5,
	0xf5, 0x8c, 0xd7, 0x3b, 0x5d, 0x5b, 0x6c, 0x25, 0x22, 0x11, 0xda, 0xe5, 0xab, 0x2f, 0xa3, 0x5a,
	0xfc, 0xaf, 0xc2, 0x28, 0xf5, 0xda, 0xd9, 0xf9, 0x31, 0x8e, 0xa6, 0x9e, 0x1b, 0xe8, 0x9e, 0x8c,
	0x25, 0xc5, 0x4f, 0x51, 0x33, 0x8b, 0xf3, 0x38, 0x05, 0xdb, 0x6a, 0x5b, 0xee, 0x64, 0x77, 0xde,
	0xbb, 0x9d, 0xc4, 0x7b, 0xa5, 0xbd, 0xc1, 0xe8, 0xf9, 0xe5, 0x72, 0x23, 0x2c, 0xb5, 0xf8, 0x10,
	0x2d, 0xc6, 0x00, 0x54, 0x42, 0x34, 0x10, 0xe4, 0x84, 0xf6, 0x23, 0xa0, 0x1f, 0x0a, 0xca, 0x09,
	0x8d, 0x24, 0xcb, 0xec, 0xbf, 0xda, 0x96, 0x3b, 0x11, 0xfc, 0xaf, 0x22, 0xbe, 0x5d, 0x2e, 0xcf,
	0x11, 0x01, 0xa9, 0x00, 0xe8, 0x9f, 0x78, 0x4c, 0xf8, 0x69, 0x2c, 0x8f, 0xbd, 0x17, 0x5c, 0x86,
	0x0b, 0x06, 0xb0, 0xad, 0xe3, 0xf7, 0xca, 0xf0, 0x7d, 0x96, 0x61, 0x17, 0xcd, 0x80, 0x28, 0x72,
	0x42, 0xa3, 0x9e, 0x24, 0x91, 0x14, 0x27, 0x94, 0xdb, 0x23, 0x8a, 0x18, 0x4e, 0x1b, 0x7b, 0x20,
	0xc9, 0xbe, 0xb2, 0xe2, 0x03, 0x34, 0x47, 0x73, 0xd2, 0x5d, 0x35, 0x22, 0x88, 0xd2, 0x38, 0xcb,
	0x18, 0x4f, 0xc0, 0x1e, 0x6d, 0x8f, 0xb8, 0x93, 0xdd, 0x07, 0xd5, 0x56, 0xb6, 0xc2, 0xcd, 0xee,
	0xaa, 0x0e, 0xdd, 0x31, 0xca, 0x70, 0x56, 0xc7, 0x6b, 0x13, 0x94, 0x36, 0xc0, 0x2f, 0x11, 0x66,
	0x9c, 0x49, 0x16, 0x0f, 0x74, 0x05, 0x50, 0x64, 0xd9, 0xe0, 0xcc, 0x1e, 0x1b, 0xa6, 0xa9, 0x99,
	0x32, 0x30, 0x90, 0x64, 0x4f, 0x87, 0xe1, 0xb7, 0x68, 0xa9, 0x9c, 0x54, 0xc1, 0xeb, 0x66, 0xd5,
	0x1c, 0x06, 0xfb, 0xaf, 0x41, 0x1c, 0x94, 0x84, 0xdf, 0xa7, 0xf5, 0x1a, 0xcd, 0x57, 0xf9, 0xf4,
	0x94, 0x72, 0x09, 0xf6, 0xb8, 0x1e, 0xc2, 0x4a, 0x75, 0x08, 0x1b, 0xb7, 0x50, 0x5b, 0x4a, 0x1b,
	0xb6, 0xe2, 0xbb, 0x46, 0xc0, 0xef, 0xd1, 0x4a, 0x8f, 0x49, 0x22, 0x18, 0x8f, 0xc8, 0x71, 0xcc,
	0x78, 0x94, 0x32, 0x1e, 0x19, 0x50, 0x24, 0x0a, 0x19, 0xc5, 0xa9, 0x28, 0xb8, 0xb4, 0xff, 0x1e,
	0xa6, 0x03, 0xa7, 0x24, 0x6d, 0x2a, 0xd0, 0x0e, 0xe3, 0x81, 0xc6, 0xec, 0x16, 0x72, 0x43, 0x43,
	0x70, 0x82, 0x96, 0xf4, 0x12, 0xeb, 0x73, 0x80, 0x3d, 0xa1, 0x9b, 0x79, 0x54, 0x6d, 0xc6, 0x2c,
	0xf3, 0x0e, 0x2e, 0xb4, 0x65, 0xbd, 0x03, 0xf0, 0xbc, 0xfa, 0xdf, 0x0b, 0xa0, 0xb9, 0x8d, 0xda,
	0x96, 0x3b, 0x15, 0x96, 0x27, 0xfc, 0x18, 0xe1, 0x41, 0x0c, 0x52, 0x25, 0x3d, 0x1a, 0x88, 0x8f,
	0x51, 0x4e, 0x81, 0x4a, 0x7b, 0xb2, 0x6d, 0xb9, 0xa3, 0xe1, 0x8c, 0xf2, 0xec, 0x1a, 0x47, 0xa8,
	0xec, 0xf8, 0x0d, 0x5a, 0x20, 0x45, 0x9e, 0x53, 0xfe, 0x2b, 0xe0, 0xa6, 0xd2, 0x29, 0x5d, 0xe9,
	0xc3, 0x6a, 0xa5, 0x9b, 0x46, 0x5e, 0x52, 0xca, 0x32, 0xe7, 0x48, 0x8d, 0x15, 0xd4, 0x4e, 0xab,
	0xf4, 0x01, 0x4b, 0x99, 0x04, 0xfb, 0x9f, 0xfa, 0x9d, 0xde, 0x86, 0x6f, 0x2b, 0x6d, 0xd8, 0x22,
	0x77, 0x8d, 0xd0, 0x21, 0xa8, 0x55, 0x57, 0x09, 0x6e, 0xa1, 0x31, 0x73, 0xd3, 0x2c, 0x3d, 0x15,
	0x73, 0xc0, 0xcf, 0x50, 0xb3, 0x5c, 0xf2, 0x50, 0x57, 0xba, 0x14, 0x77, 0xde, 0xa1, 0xd9, 0x9a,
	0x8a, 0xee, 0xc9, 0xb1, 0x8e, 0xc6, 0x74, 0x73, 0xc3, 0xa5, 0x30, 0xda, 0xce, 0x11, 0x5a, 0xb8,
	0x67, 0xf5, 0x7f, 0xb4, 0x93, 0x20, 0x38, 0xbf, 0x72, 0xac, 0x8b, 0x2b, 0xc7, 0xfa, 0x7e, 0xe5,
	0x58, 0x5f, 0xae, 0x9d, 0xc6, 0xc5, 0xb5, 0xd3, 0xf8, 0x7a, 0xed, 0x34, 0x0e, 0xdd, 0x84, 0xc9,
	0xe3, 0xa2, 0xe7, 0x11, 0x91, 0xfa, 0x6a, 0x1b, 0x4f, 0x44, 0x9e, 0xe8, 0x8f, 0xbe, 0xff, 0xe9,
	0xe6, 0xf1, 0x95, 0x67, 0x19, 0x85, 0x5e, 0x53, 0xbf, 0xbc, 0xeb, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x13, 0x94, 0xef, 0x74, 0xdc, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CurrentOutflowLimits) > 0 {
		for iNdEx := len(m.CurrentOutflowLimits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CurrentOutflowLimits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.CurrentOutflowAmounts) > 0 {
		for iNdEx := len(m.CurrentOutflowAmounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CurrentOutflowAmounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.LastOutflowReset != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastOutflowReset))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Pauser) > 0 {
		i -= len(m.Pauser)
		copy(dAtA[i:], m.Pauser)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Pauser)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.TokenMinBridgeOutAmounts) > 0 {
		for iNdEx := len(m.TokenMinBridgeOutAmounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenMinBridgeOutAmounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	{
		size := m.BitcoinChainMinBridgeOutAmount.Size()
		i -= size
		if _, err := m.BitcoinChainMinBridgeOutAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if len(m.AssetsUnlockedEvents) > 0 {
		for iNdEx := len(m.AssetsUnlockedEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AssetsUnlockedEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	{
		size := m.AssetsUnlockedSequenceTip.Size()
		i -= size
		if _, err := m.AssetsUnlockedSequenceTip.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.InitialBtcSupply.Size()
		i -= size
		if _, err := m.InitialBtcSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Erc20TokensMappings) > 0 {
		for iNdEx := len(m.Erc20TokensMappings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Erc20TokensMappings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.SourceBtcToken) > 0 {
		i -= len(m.SourceBtcToken)
		copy(dAtA[i:], m.SourceBtcToken)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SourceBtcToken)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.AssetsLockedSequenceTip.Size()
		i -= size
		if _, err := m.AssetsLockedSequenceTip.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CurrentOutflowAmount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentOutflowAmount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentOutflowAmount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CurrentOutflowLimit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentOutflowLimit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentOutflowLimit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Limit.Size()
		i -= size
		if _, err := m.Limit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TokenMinBridgeOutAmount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenMinBridgeOutAmount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenMinBridgeOutAmount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.AssetsLockedSequenceTip.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.SourceBtcToken)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Erc20TokensMappings) > 0 {
		for _, e := range m.Erc20TokensMappings {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.InitialBtcSupply.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.AssetsUnlockedSequenceTip.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.AssetsUnlockedEvents) > 0 {
		for _, e := range m.AssetsUnlockedEvents {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.BitcoinChainMinBridgeOutAmount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.TokenMinBridgeOutAmounts) > 0 {
		for _, e := range m.TokenMinBridgeOutAmounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.Pauser)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.LastOutflowReset != 0 {
		n += 1 + sovGenesis(uint64(m.LastOutflowReset))
	}
	if len(m.CurrentOutflowAmounts) > 0 {
		for _, e := range m.CurrentOutflowAmounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CurrentOutflowLimits) > 0 {
		for _, e := range m.CurrentOutflowLimits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *CurrentOutflowAmount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *CurrentOutflowLimit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Limit.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *TokenMinBridgeOutAmount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetsLockedSequenceTip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AssetsLockedSequenceTip.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceBtcToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceBtcToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Erc20TokensMappings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Erc20TokensMappings = append(m.Erc20TokensMappings, &ERC20TokenMapping{})
			if err := m.Erc20TokensMappings[len(m.Erc20TokensMappings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBtcSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialBtcSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetsUnlockedSequenceTip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AssetsUnlockedSequenceTip.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetsUnlockedEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetsUnlockedEvents = append(m.AssetsUnlockedEvents, &AssetsUnlockedEvent{})
			if err := m.AssetsUnlockedEvents[len(m.AssetsUnlockedEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BitcoinChainMinBridgeOutAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BitcoinChainMinBridgeOutAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenMinBridgeOutAmounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenMinBridgeOutAmounts = append(m.TokenMinBridgeOutAmounts, &TokenMinBridgeOutAmount{})
			if err := m.TokenMinBridgeOutAmounts[len(m.TokenMinBridgeOutAmounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pauser", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pauser = append(m.Pauser[:0], dAtA[iNdEx:postIndex]...)
			if m.Pauser == nil {
				m.Pauser = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastOutflowReset", wireType)
			}
			m.LastOutflowReset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastOutflowReset |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentOutflowAmounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentOutflowAmounts = append(m.CurrentOutflowAmounts, &CurrentOutflowAmount{})
			if err := m.CurrentOutflowAmounts[len(m.CurrentOutflowAmounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentOutflowLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentOutflowLimits = append(m.CurrentOutflowLimits, &CurrentOutflowLimit{})
			if err := m.CurrentOutflowLimits[len(m.CurrentOutflowLimits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrentOutflowAmount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentOutflowAmount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentOutflowAmount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = append(m.Token[:0], dAtA[iNdEx:postIndex]...)
			if m.Token == nil {
				m.Token = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrentOutflowLimit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentOutflowLimit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentOutflowLimit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = append(m.Token[:0], dAtA[iNdEx:postIndex]...)
			if m.Token == nil {
				m.Token = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Limit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TokenMinBridgeOutAmount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenMinBridgeOutAmount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenMinBridgeOutAmount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = append(m.Token[:0], dAtA[iNdEx:postIndex]...)
			if m.Token == nil {
				m.Token = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
