# hadolint global ignore=DL3018
FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod download && \
    CGO_ENABLED=0 GOOS=linux go build -o metrics-scraper ./cmd/metrics-scraper

FROM alpine:3.21.3

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /

COPY --from=builder /app/metrics-scraper .

ENTRYPOINT ["./metrics-scraper"]
