# hadolint global ignore=DL3018
FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod download && \
    CGO_ENABLED=0 GOOS=linux go build -o bridge-worker ./cmd/bridge-worker

FROM alpine:3.21.3

RUN apk --no-cache add ca-certificates tzdata

RUN mkdir -p  /etc/bridge-worker

WORKDIR /

COPY --from=builder /app/bridge-worker .

ENTRYPOINT ["./bridge-worker"]
