apiVersion: apps/v1
kind: Deployment
metadata:
  name: contracts-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contracts-exporter
  template:
    metadata:
      labels:
        app: contracts-exporter
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: contracts-exporter
          image: rtwatts/contracts-exporter:v2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9115
          volumeMounts:
            - name: contracts-exporter-config
              mountPath: /etc/contracts-exporter
          env:
            - name: PORT
              value: "9115"
            - name: ADDRESSES_FILE
              value: /etc/contracts-exporter/addresses.txt
            - name: CONTRACTS_FILE
              value: /etc/contracts-exporter/contracts.txt
            - name: PREFIX
              value: mezo_
            - name: CHAIN_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: rpc-url
                  key: MEZO

      volumes:
        - name: contracts-exporter-config
          configMap:
            name: contracts-exporter-config
