image: mezo/mezod
# tag: ""

env:
  NETWORK: testnet
  MEZOD_CHAIN_ID: mezo_31611-1
  PUBLIC_IP: "34.70.22.86" # mezo-staging-node-4-external-ip
  MEZOD_MONIKER: "mezo-node-4"

customConfigs:
  enabled: true
  appTomlTxt: ""
  clientTomlTxt: ""
  configTomlTxt: |
    statesync.enable=true
    statesync.rpc_servers=mezo-node-3.test.mezo.org:26657,mezo-node-3.test.mezo.org:26657
    statesync.trust_height=5554501
    statesync.trust_hash=1A5227D45C4EF9F0B39C2815DD40D85032403EA81ABF112FAEC757BAC29F36E8

secrets:
  credentials: "mezo-node-4" # created manually

storage:
  className: "premium-rwo"
  size: "100Gi"
  useDataSource:
    enabled: true
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: "mezo-node-data-mezo-node-4-0"

service:
  public:
    loadBalancerIP: "34.70.22.86" # same as PUBLIC_IP

labels:
  app: mezo
  type: node
  id: "4"

maintenanceMode: false
