image: us-central1-docker.pkg.dev/mezo-test-420708/mezo-staging-docker-public/mezod
tag: v3.0.1-rc1

env:
  NETWORK: testnet
  MEZOD_CHAIN_ID: mezo_31611-1
  PUBLIC_IP: "34.170.77.124" # mezo-staging-node-3-external-ip
  MEZOD_MONIKER: "mezo-node-3"

secrets:
  credentials: "mezo-node-3" # created manually

storage:
  className: "premium-rwo"
  size: "100Gi"
  useDataSource:
    enabled: true
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: "mezo-node-data-mezo-node-3-0"

service:
  public:
    loadBalancerIP: "34.170.77.124" # same as PUBLIC_IP

labels:
  app: mezo
  type: node
  id: "3"

maintenanceMode: false
