# This file is used to override the default values in the Bitnami PostgreSQL chart.
# See: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml

global:
  postgresql:
    auth:
      database: blockscout

      # Added after the first deployment as a workaround for
      # https://github.com/bitnami/charts/issues/16417
      # https://github.com/bitnami/charts/issues/15073
      postgresPassword: secretref+k8s://v1/Secret/default/postgresql/postgres-password

image:
  tag: 15 # Use version supported by Blockscout

primary:
  resourcesPreset: "xlarge"
  extraEnvVars:
    - name: POSTGRESQL_MAX_CONNECTIONS
      value: "200"
  persistence:
    size: 100Gi # Default is only 8Gi
