// Code generated by MockGen. DO NOT EDIT.
// Source: bridge-worker/bridge_worker.go
//
// Generated by this command:
//
//	mockgen -source=bridge-worker/bridge_worker.go -destination=bridge-worker/mock_ethereum_chain_test.go -package=bridgeworker TbtcBridgeContract
//

// Package bridgeworker is a generated GoMock package.
package bridgeworker

import (
	context "context"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	portal "github.com/mezo-org/mezod/ethereum/bindings/portal"
	tbtc "github.com/mezo-org/mezod/ethereum/bindings/tbtc"
	gomock "go.uber.org/mock/gomock"
)

// MockEthereumChain is a mock of EthereumChain interface.
type MockEthereumChain struct {
	ctrl     *gomock.Controller
	recorder *MockEthereumChainMockRecorder
	isgomock struct{}
}

// MockEthereumChainMockRecorder is the mock recorder for MockEthereumChain.
type MockEthereumChainMockRecorder struct {
	mock *MockEthereumChain
}

// NewMockEthereumChain creates a new mock instance.
func NewMockEthereumChain(ctrl *gomock.Controller) *MockEthereumChain {
	mock := &MockEthereumChain{ctrl: ctrl}
	mock.recorder = &MockEthereumChainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthereumChain) EXPECT() *MockEthereumChainMockRecorder {
	return m.recorder
}

// CurrentBlock mocks base method.
func (m *MockEthereumChain) CurrentBlock() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBlock")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentBlock indicates an expected call of CurrentBlock.
func (mr *MockEthereumChainMockRecorder) CurrentBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBlock", reflect.TypeOf((*MockEthereumChain)(nil).CurrentBlock))
}

// FinalizedBlock mocks base method.
func (m *MockEthereumChain) FinalizedBlock(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizedBlock", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizedBlock indicates an expected call of FinalizedBlock.
func (mr *MockEthereumChainMockRecorder) FinalizedBlock(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizedBlock", reflect.TypeOf((*MockEthereumChain)(nil).FinalizedBlock), ctx)
}

// WatchBlocks mocks base method.
func (m *MockEthereumChain) WatchBlocks(ctx context.Context) <-chan uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchBlocks", ctx)
	ret0, _ := ret[0].(<-chan uint64)
	return ret0
}

// WatchBlocks indicates an expected call of WatchBlocks.
func (mr *MockEthereumChainMockRecorder) WatchBlocks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchBlocks", reflect.TypeOf((*MockEthereumChain)(nil).WatchBlocks), ctx)
}

// MockMezoBridgeContract is a mock of MezoBridgeContract interface.
type MockMezoBridgeContract struct {
	ctrl     *gomock.Controller
	recorder *MockMezoBridgeContractMockRecorder
	isgomock struct{}
}

// MockMezoBridgeContractMockRecorder is the mock recorder for MockMezoBridgeContract.
type MockMezoBridgeContractMockRecorder struct {
	mock *MockMezoBridgeContract
}

// NewMockMezoBridgeContract creates a new mock instance.
func NewMockMezoBridgeContract(ctrl *gomock.Controller) *MockMezoBridgeContract {
	mock := &MockMezoBridgeContract{ctrl: ctrl}
	mock.recorder = &MockMezoBridgeContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMezoBridgeContract) EXPECT() *MockMezoBridgeContractMockRecorder {
	return m.recorder
}

// PastAssetsUnlockConfirmedEvents mocks base method.
func (m *MockMezoBridgeContract) PastAssetsUnlockConfirmedEvents(startBlock uint64, endBlock *uint64, unlockSequenceNumber []*big.Int, recipient [][]byte, token []common.Address) ([]*portal.MezoBridgeAssetsUnlockConfirmed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PastAssetsUnlockConfirmedEvents", startBlock, endBlock, unlockSequenceNumber, recipient, token)
	ret0, _ := ret[0].([]*portal.MezoBridgeAssetsUnlockConfirmed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PastAssetsUnlockConfirmedEvents indicates an expected call of PastAssetsUnlockConfirmedEvents.
func (mr *MockMezoBridgeContractMockRecorder) PastAssetsUnlockConfirmedEvents(startBlock, endBlock, unlockSequenceNumber, recipient, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PastAssetsUnlockConfirmedEvents", reflect.TypeOf((*MockMezoBridgeContract)(nil).PastAssetsUnlockConfirmedEvents), startBlock, endBlock, unlockSequenceNumber, recipient, token)
}

// PendingBTCWithdrawals mocks base method.
func (m *MockMezoBridgeContract) PendingBTCWithdrawals(arg0 [32]byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingBTCWithdrawals", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingBTCWithdrawals indicates an expected call of PendingBTCWithdrawals.
func (mr *MockMezoBridgeContractMockRecorder) PendingBTCWithdrawals(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingBTCWithdrawals", reflect.TypeOf((*MockMezoBridgeContract)(nil).PendingBTCWithdrawals), arg0)
}

// TbtcToken mocks base method.
func (m *MockMezoBridgeContract) TbtcToken() (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TbtcToken")
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TbtcToken indicates an expected call of TbtcToken.
func (mr *MockMezoBridgeContractMockRecorder) TbtcToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TbtcToken", reflect.TypeOf((*MockMezoBridgeContract)(nil).TbtcToken))
}

// WithdrawBTC mocks base method.
func (m *MockMezoBridgeContract) WithdrawBTC(entry portal.MezoBridgeAssetsUnlocked, walletPubKeyHash [20]byte, mainUtxo portal.BitcoinTxUTXO) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawBTC", entry, walletPubKeyHash, mainUtxo)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithdrawBTC indicates an expected call of WithdrawBTC.
func (mr *MockMezoBridgeContractMockRecorder) WithdrawBTC(entry, walletPubKeyHash, mainUtxo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawBTC", reflect.TypeOf((*MockMezoBridgeContract)(nil).WithdrawBTC), entry, walletPubKeyHash, mainUtxo)
}

// MockTbtcBridgeContract is a mock of TbtcBridgeContract interface.
type MockTbtcBridgeContract struct {
	ctrl     *gomock.Controller
	recorder *MockTbtcBridgeContractMockRecorder
	isgomock struct{}
}

// MockTbtcBridgeContractMockRecorder is the mock recorder for MockTbtcBridgeContract.
type MockTbtcBridgeContractMockRecorder struct {
	mock *MockTbtcBridgeContract
}

// NewMockTbtcBridgeContract creates a new mock instance.
func NewMockTbtcBridgeContract(ctrl *gomock.Controller) *MockTbtcBridgeContract {
	mock := &MockTbtcBridgeContract{ctrl: ctrl}
	mock.recorder = &MockTbtcBridgeContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTbtcBridgeContract) EXPECT() *MockTbtcBridgeContractMockRecorder {
	return m.recorder
}

// PastNewWalletRegisteredEvents mocks base method.
func (m *MockTbtcBridgeContract) PastNewWalletRegisteredEvents(startBlock uint64, endBlock *uint64, ecdsaWalletID [][32]byte, walletPubKeyHash [][20]byte) ([]*tbtc.BridgeNewWalletRegistered, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PastNewWalletRegisteredEvents", startBlock, endBlock, ecdsaWalletID, walletPubKeyHash)
	ret0, _ := ret[0].([]*tbtc.BridgeNewWalletRegistered)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PastNewWalletRegisteredEvents indicates an expected call of PastNewWalletRegisteredEvents.
func (mr *MockTbtcBridgeContractMockRecorder) PastNewWalletRegisteredEvents(startBlock, endBlock, ecdsaWalletID, walletPubKeyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PastNewWalletRegisteredEvents", reflect.TypeOf((*MockTbtcBridgeContract)(nil).PastNewWalletRegisteredEvents), startBlock, endBlock, ecdsaWalletID, walletPubKeyHash)
}

// PendingRedemptions mocks base method.
func (m *MockTbtcBridgeContract) PendingRedemptions(redemptionKey *big.Int) (tbtc.RedemptionRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingRedemptions", redemptionKey)
	ret0, _ := ret[0].(tbtc.RedemptionRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingRedemptions indicates an expected call of PendingRedemptions.
func (mr *MockTbtcBridgeContractMockRecorder) PendingRedemptions(redemptionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingRedemptions", reflect.TypeOf((*MockTbtcBridgeContract)(nil).PendingRedemptions), redemptionKey)
}

// RedemptionDustThreshold mocks base method.
func (m *MockTbtcBridgeContract) RedemptionDustThreshold() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedemptionDustThreshold")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RedemptionDustThreshold indicates an expected call of RedemptionDustThreshold.
func (mr *MockTbtcBridgeContractMockRecorder) RedemptionDustThreshold() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedemptionDustThreshold", reflect.TypeOf((*MockTbtcBridgeContract)(nil).RedemptionDustThreshold))
}

// Wallets mocks base method.
func (m *MockTbtcBridgeContract) Wallets(walletPublicKeyHash [20]byte) (tbtc.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wallets", walletPublicKeyHash)
	ret0, _ := ret[0].(tbtc.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wallets indicates an expected call of Wallets.
func (mr *MockTbtcBridgeContractMockRecorder) Wallets(walletPublicKeyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wallets", reflect.TypeOf((*MockTbtcBridgeContract)(nil).Wallets), walletPublicKeyHash)
}

// MockbridgeWorkerJob is a mock of bridgeWorkerJob interface.
type MockbridgeWorkerJob struct {
	ctrl     *gomock.Controller
	recorder *MockbridgeWorkerJobMockRecorder
	isgomock struct{}
}

// MockbridgeWorkerJobMockRecorder is the mock recorder for MockbridgeWorkerJob.
type MockbridgeWorkerJobMockRecorder struct {
	mock *MockbridgeWorkerJob
}

// NewMockbridgeWorkerJob creates a new mock instance.
func NewMockbridgeWorkerJob(ctrl *gomock.Controller) *MockbridgeWorkerJob {
	mock := &MockbridgeWorkerJob{ctrl: ctrl}
	mock.recorder = &MockbridgeWorkerJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbridgeWorkerJob) EXPECT() *MockbridgeWorkerJobMockRecorder {
	return m.recorder
}

// run mocks base method.
func (m *MockbridgeWorkerJob) run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "run", ctx)
}

// run indicates an expected call of run.
func (mr *MockbridgeWorkerJobMockRecorder) run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "run", reflect.TypeOf((*MockbridgeWorkerJob)(nil).run), ctx)
}
