apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: bridge-worker
      app.kubernetes.io/managed-by: kustomize

