global:
  scrape_interval: 15s # default: 1m

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: alertmanager
    static_configs:
      - targets: [alertmanager:9093]

  # Ref:
  # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#docker_sd_config
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: [prometheus.scrape=true]
    relabel_configs:
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_network_ip, __meta_docker_container_label_prometheus_port]
        target_label: __address__
        regex: (.+);(.+)
        replacement: $1:$2
      - source_labels: [__meta_docker_container_label_prometheus_path]
        target_label: __metrics_path__
        replacement: $1
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1

alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]

rule_files:
  - alerts.yaml
