apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-scraper
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-scraper
  template:
    metadata:
      labels:
        app: metrics-scraper
    spec:
      containers:
        - name: metrics-scraper
          image: mezo/metrics-scraper:latest
          imagePullPolicy: Always
          args:
            - --chain-id=$(CHAIN_ID)
            - --nodes-config=/etc/metrics-scraper/nodes-config.json
            - --mezo-rpc-url=$(MEZO_RPC_URL)
            - --ethereum-rpc-url=$(ETHEREUM_RPC_URL)
          env:
            - name: CHAIN_ID
              valueFrom:
                secretKeyRef:
                  name: metrics-scraper-config
                  key: chain-id
            - name: MEZO_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: metrics-scraper-config
                  key: mezo-rpc-url
            - name: ETHEREUM_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: metrics-scraper-config
                  key: ethereum-rpc-url
          ports:
            - containerPort: 2112
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: metrics-scraper-config
              mountPath: /etc/metrics-scraper
      volumes:
        - name: metrics-scraper-config
          secret:
            secretName: metrics-scraper-config
            items:
              - key: nodes-config.json
                path: nodes-config.json
