apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      evaluation_interval: 2s

    rule_files:
      - "alert_rules.yml"

    scrape_configs:
      - job_name: 'metrics-scraper'
        static_configs:
          - targets: ['metrics-scraper:2112']
      - job_name: 'api-metrics'
        metrics_path: /api/v2/metrics
        static_configs:
          - targets: ['api.mezo.org']
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]  # Look for a HTTP 200 response.
        static_configs: 
          - targets:
            - https://mezo.org
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115 
      - job_name: 'contracts-exporter'
        metrics_path: /metrics
        static_configs:
          - targets: ['contracts-exporter:9115']
      - job_name: 'musd-exporter'
        metrics_path: /metrics
        static_configs:
          - targets: ['musd-exporter:9116']

  alert_rules.yml: |
    groups:
      - name: musd_alerts
        rules:
          - alert: PCVDebtToPayZero
            expr: mezo_contract_function_result{contract="PCV",function="debtToPay"} == 0
            for: 1m
            labels:
              severity: warning
              contract: PCV
            annotations:
              summary: "PCV contract debt to pay is zero"
              description: "The PCV contract debtToPay function returned 0."
          - alert: ActivePoolBTCInsufficient
            expr: |
              (
                (mezo_contract_function_result{contract="ActivePool",function="getCollateralBalance"} * mezo_contract_function_result{contract="PriceFeed",function="fetchPrice"} / 1e18) 
                < 
                0.8 * (mezo_contract_function_result{contract="MUSD",function="totalSupply"} - mezo_contract_function_result{contract="StabilityPool",function="getTotalMUSDDeposits"}) / 1e18
              ) 
              and 
              mezo_contract_function_result{contract="PCV",function="debtToPay"} > 0
            for: 5m
            labels:
              severity: critical
              contract: ActivePool
            annotations:
              summary: "Active Pool BTC insufficient for redemptions"
              description: "Active Pool BTC balance is less than 80% of circulating MUSD supply. This could lead to inability to honor redemptions."
