---
x-volumes: &volumes
  volumes:
    - type: bind
      source: ./tmp/mezod
      target: ${MEZOD_HOME}
    # Commented, as long as the keyring-dir flag is not supported by the "mezod start" command.
    # - type: bind
    #   source: ./tmp/keyring
    #   target: ${MEZOD_KEYRING_DIR}

services:
  #
  # SECTION: operations
  #
  cli:
    container_name: cli
    image: ${DOCKER_IMAGE_DEBUG}
    platform: linux/amd64
    deploy:
      # Make sure that the service won't run for "docker compose up".
      # It is intended to be run manually.
      replicas: 0
    entrypoint: ["sh"]
    working_dir: ${MEZOD_HOME}
    <<: *volumes
    networks:
      - mezo

  #
  # PHASE: initialization
  #
  init-keyring:
    container_name: init-keyring
    image: ${DOCKER_IMAGE_DEBUG}
    platform: linux/amd64
    entrypoint: ["sh", "-c"]
    command:
      - |
        echo "Prepare keyring..."
        (echo $KEYRING_SEED; echo $KEYRING_PASSWORD; echo $KEYRING_PASSWORD) \
          | mezod keys add \
            ${KEYRING_KEY_NAME} \
            --home=${MEZOD_HOME} \
            --keyring-backend=${MEZOD_KEYRING_BACKEND} \
            --keyring-dir=${MEZOD_KEYRING_DIR} \
            --recover
        echo "Keyring prepared!"
    <<: *volumes
    restart: on-failure:2
    networks:
      - mezo

  init-config:
    container_name: init-config
    image: ${DOCKER_IMAGE_PRODUCTION}
    platform: linux/amd64
    command:
      - mezod
      - init
      - ${MEZOD_MONIKER}
      - --chain-id=${MEZOD_CHAIN_ID}
      - --home=${MEZOD_HOME}
      - --keyring-backend=${MEZOD_KEYRING_BACKEND}
      # - --keyring-dir=${MEZOD_KEYRING_DIR}
    <<: *volumes
    restart: on-failure:2
    depends_on:
      init-keyring:
        condition: service_completed_successfully
    networks:
      - mezo

  # Download genesis.json as long as it is not provided by the "init-config" service.
  genesis:
    container_name: genesis
    image: mikefarah/yq
    platform: linux/amd64
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo >${MEZOD_HOME}/config/genesis.json
        wget --output-document=/tmp/genesis.yaml ${SETUP_GENESIS_URL} || { echo "Genesis file not found!"; exit 1; }
        yq '.data["genesis.json"]' /tmp/genesis.yaml > ${MEZOD_HOME}/config/genesis.json
        echo "Genesis file downloaded!"
    <<: *volumes
    depends_on:
      init-config:
        condition: service_completed_successfully

  #
  # PHASE: runtime
  #
  ethereum-sidecar:
    container_name: ethereum-sidecar
    image: ${DOCKER_IMAGE_PRODUCTION}
    platform: linux/amd64
    command:
      - mezod
      - ethereum-sidecar
      - --log_format=${MEZOD_LOG_FORMAT}
      - --ethereum-sidecar.server.ethereum-node-address=${MEZOD_ETHEREUM_SIDECAR_SERVER_ETHEREUM_NODE_ADDRESS}
    restart: always
    deploy:
      resources:
        reservations: # TODO: verify on Linux
          cpus: '1'
          memory: 100M
    depends_on:
      genesis:
        condition: service_completed_successfully
    expose:
      - 7500
    networks:
      - mezo
    cap_drop:
      - ALL

  connect-sidecar:
    container_name: connect-sidecar
    image: ghcr.io/skip-mev/connect-sidecar:v2.1.1
    # Dockerfile: https://github.com/skip-mev/connect/blob/main/contrib/images/connect.sidecar.prod.Dockerfile
    platform: linux/amd64
    entrypoint: []
    command:
      - connect
      - --log-disable-file-rotation
      - --port=${CONNECT_SIDECAR_PORT}
      # - --metrics-enabled
      # - --metrics-prometheus-address=${CONNECT_SIDECAR_METRICS_PROMETHEUS_ADDRESS}
      - --market-map-endpoint=mezod:9090
    depends_on:
      genesis:
        condition: service_completed_successfully
    networks:
      - mezo
    cap_drop:
      - ALL

  mezod:
    container_name: mezod
    image: ${DOCKER_IMAGE_PRODUCTION}
    platform: linux/amd64
    command:
      - mezod
      - start
      - --log_format=${MEZOD_LOG_FORMAT}
      - --chain-id=${MEZOD_CHAIN_ID}
      - --home=${MEZOD_HOME}
      - --keyring-backend=${MEZOD_KEYRING_BACKEND}
      # - --keyring-dir=${MEZOD_KEYRING_DIR}
      - --moniker=${MEZOD_MONIKER}
      - --p2p.seeds=${MEZOD_P2P_SEEDS}
      - --ethereum-sidecar.client.server-address=${MEZOD_ETHEREUM_SIDECAR_CLIENT_SERVER_ADDRESS}
    <<: *volumes
    # restart: always
    deploy:
      resources:
        reservations: # TODO: verify on Linux
          cpus: '1'
          memory: 100M
    ports:
      - 26656:26656 # p2p
      - 26657:26657 # rpc
      - 1317:1317   # api
      - 9090:9090   # grpc
      - 8545:8545   # json-rpc
      - 8546:8546   # json-rpc-ws
    networks:
      - mezo
    depends_on:
      genesis:
        condition: service_completed_successfully
      ethereum-sidecar:
        condition: service_started
      connect-sidecar:
        condition: service_started
    healthcheck:
      test: ["CMD", "cat", "${MEZOD_HOME}/config/genesis.json"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 1s
      start_interval: 1s
    cap_drop:
      - ALL

networks:
  mezo:
    driver: bridge
