# This file is used to override the default values in the Blockscout chart.
# See: https://github.com/blockscout/helm-charts/blob/main/charts/blockscout-stack/values.yaml

config:
  network:
    id: 31611
    name: Mezo
    shortname: Mezo
    currency:
      name: Bitcoin
      symbol: BTC
      decimals: 18
  account:
    enabled: false # This is false by default but disable it explicitly. As long as this feature is disable, Redis is not needed.
  testnet: true
  prometheus:
    enabled: false # This won't be needed for now.

blockscout:
  ingress:
    enabled: true
    hostname: api.explorer.test.mezo.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: mezo-staging-blockscout-api-external-ip
      ingress.gcp.kubernetes.io/pre-shared-cert: mezo-staging-explorer-ssl-certificate
  readinessProbe:
    params:
      # The default config sets timeoutSeconds > periodSeconds which is faulty.
      periodSeconds: 30
      timeoutSeconds: 10
  env:
    ETHEREUM_JSONRPC_VARIANT: geth
    ETHEREUM_JSONRPC_HTTP_URL: http://mezo-node-0.default.svc.cluster.local:8545
    ETHEREUM_JSONRPC_WS_URL: ws://mezo-node-0.default.svc.cluster.local:8546
    ETHEREUM_JSONRPC_FALLBACK_HTTP_URL: http://mezo-node-1.default.svc.cluster.local:8545
    NETWORK: Mezo
    SUBNETWORK: Testnet
    BLOCKSCOUT_PROTOCOL: https
    SECRET_KEY_BASE: K4rV3pnwzqGMRZNbyWKryw6Co4qcvm9LvZhUpuf4qftDTsZMjzz4pzgVPZcUXMtf # Just an arbitrary 64-char string
    POOL_SIZE: 80 # Increased from the default value of 50 based on the original Blockscout Docker Compose config
    ECTO_USE_SSL: false # Switched off based on the original Blockscout Docker Compose config
    CONTRACT_VERIFICATION_ALLOWED_SOLIDITY_EVM_VERSIONS: homestead,tangerineWhistle,spuriousDragon,byzantium,constantinople,petersburg,istanbul,berlin,london,default
    CONTRACT_VERIFICATION_ALLOWED_VYPER_EVM_VERSIONS: byzantium,constantinople,petersburg,istanbul,berlin,london,default
    INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: true # Disable internal transactions fetcher for now. It does not work in all cases and causes the whole indexer to stop.
    CACHE_ADDRESS_TRANSACTIONS_COUNTER_PERIOD: 5m
  extraEnv:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: postgres-password # Created automatically by the Bitnami PostgreSQL chart
    - name: DATABASE_URL
      value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql.default.svc.cluster.local:5432/blockscout

frontend:
  ingress:
    enabled: true
    hostname: explorer.test.mezo.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: mezo-staging-blockscout-app-external-ip
      ingress.gcp.kubernetes.io/pre-shared-cert: mezo-staging-explorer-ssl-certificate
  readinessProbe:
    params:
      # The default config sets timeoutSeconds > periodSeconds which is faulty.
      periodSeconds: 30
      timeoutSeconds: 10
  env:
    NEXT_PUBLIC_API_PROTOCOL: https
    NEXT_PUBLIC_APP_PROTOCOL: https
    NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: wss
    NEXT_PUBLIC_API_SPEC_URL: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml
    NEXT_PUBLIC_AD_BANNER_PROVIDER: none # Disable ads

stats:
  enabled: false # This won't be needed for now.
