apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common/monitoring
  - prometheus/configmap.yaml
  - ingress.yaml

patches:
  - path: grafana/deployement-patch.yaml

configMapGenerator:
  - name: grafana-dashboards-mezo
    files:
      - grafana/dashboards/mezo-nodes-public.json
      - grafana/dashboards/mezo-portal.json

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: generated

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: staging

namespace: monitoring
