helmDefaults:
  kubeContext: gke_mezo-test-420708_us-central1_mezo-staging-gke-cluster

repositories:
  - name: mezo-org
    url: https://mezo-org.github.io/validator-kit
  - name: blockscout
    url: https://blockscout.github.io/helm-charts

releases:
  - name: mezo-node-0
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 1.6.0
    labels:
      type: validator
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-0.yaml

  - name: mezo-node-1
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 1.6.0
    labels:
      type: validator
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-1.yaml

  - name: mezo-node-2
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 1.6.0
    labels:
      type: validator
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-2.yaml

  - name: mezo-node-3
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 1.6.0
    labels:
      type: validator
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-3.yaml

  - name: mezo-node-4
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 1.6.0
    labels:
      type: validator
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-4.yaml

  - name: postgresql
    installed: true
    namespace: default
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 15.2.10
    values:
      - ./values/postgresql.yaml

  - name: blockscout-stack
    installed: true
    namespace: default
    chart: blockscout/blockscout-stack
    version: 1.5.0
    values:
      - ./values/blockscout-stack.yaml
