{
 "title": "Accounts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Account Balances on Mezo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "BTC" } },
   "targets": [
    { "expr": "mezo_account_balance", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Account Balances on Ethereum",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    { "expr": "ethereum_account_balance", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Account Balances on Base",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    { "expr": "base_account_balance", "legendFormat": "{{name}}" }
   ]
  }
 ]
}