{
 "title": "Bridge",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pending bridge-ins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pending_assets_locked{chain_id=\"mezo_31612-1\"}"
    }
   ]
  },
  {
   "title": "Pending bridge-outs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pending_assets_unlocked{chain_id=\"mezo_31612-1\"}"
    }
   ]
  },
  {
   "title": "Bridge validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "ethereum_bridge_val_balance{chain_id=\"mezo_31612-1\"}",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}