{
 "title": "Mezo Nodes (Public)",
 "tags": [
  "public",
  "mezo"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(chain_id) (sum by(moniker) (up{chain_id=\"mezo_31611-1\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethereum sidecar connectivity",
   "type": "timeseries",
   "description": "Provides information on whether the node is connected to the ethereum sidecar.",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "min by(moniker) (ethereum_sidecar_connectivity{chain_id=\"mezo_31611-1\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Connect sidecar connectivity",
   "type": "timeseries",
   "description": "Provides information on whether the node is connected to the connect sidecar.",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "min by(moniker) (connect_sidecar_connectivity{chain_id=\"mezo_31611-1\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Uptime (experimental)",
   "type": "state-timeline",
   "gridPos": { "h": 25, "w": 13, "x": 11, "y": 40 },
   "targets": [
    {
     "expr": "min by(moniker) (up{chain_id=\"mezo_31611-1\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  }
 ]
}