{
 "title": "Mezo Portal",
 "time": { "from": "now-5d", "to": "now" },
 "panels": [
  {
   "title": "Portal API Services Availability",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mezo_portal_api_status", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Portal Website Availability",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"blackbox\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Portal API Response Times",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mezo_portal_api_duration_milliseconds",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Portal API Response Duration",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}