// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mezo/ethereum_sidecar/v1/ethereum_sidecar_bridge_out.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/mezo-org/mezod/x/bridge/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AssetsUnlockedEntriesRequest is the request type for the
// AssetsUnlockedEntries query.
type AssetsUnlockedEntriesRequest struct {
	// sequence_start is the start of the sequence range (inclusive). If null,
	// unbounded on the lower side.
	SequenceStart cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=sequence_start,json=sequenceStart,proto3,customtype=cosmossdk.io/math.Int" json:"sequence_start"`
	// sequence_end is the end of the sequence range (exclusive). If null,
	// unbounded on the upper side.
	SequenceEnd cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=sequence_end,json=sequenceEnd,proto3,customtype=cosmossdk.io/math.Int" json:"sequence_end"`
}

func (m *AssetsUnlockedEntriesRequest) Reset()         { *m = AssetsUnlockedEntriesRequest{} }
func (m *AssetsUnlockedEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AssetsUnlockedEntriesRequest) ProtoMessage()    {}
func (*AssetsUnlockedEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e84e01faa13b80, []int{0}
}
func (m *AssetsUnlockedEntriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetsUnlockedEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetsUnlockedEntriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetsUnlockedEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetsUnlockedEntriesRequest.Merge(m, src)
}
func (m *AssetsUnlockedEntriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *AssetsUnlockedEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetsUnlockedEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssetsUnlockedEntriesRequest proto.InternalMessageInfo

// AssetsUnlockedEntriesResponse is the response type for the
// AssetsUnlockedEntries query.
type AssetsUnlockedEntriesResponse struct {
	// entries contains a list of AssetsUnlocked.
	Entries []*types.AssetsUnlocked `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (m *AssetsUnlockedEntriesResponse) Reset()         { *m = AssetsUnlockedEntriesResponse{} }
func (m *AssetsUnlockedEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AssetsUnlockedEntriesResponse) ProtoMessage()    {}
func (*AssetsUnlockedEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e84e01faa13b80, []int{1}
}
func (m *AssetsUnlockedEntriesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetsUnlockedEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetsUnlockedEntriesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetsUnlockedEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetsUnlockedEntriesResponse.Merge(m, src)
}
func (m *AssetsUnlockedEntriesResponse) XXX_Size() int {
	return m.Size()
}
func (m *AssetsUnlockedEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetsUnlockedEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssetsUnlockedEntriesResponse proto.InternalMessageInfo

func (m *AssetsUnlockedEntriesResponse) GetEntries() []*types.AssetsUnlocked {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*AssetsUnlockedEntriesRequest)(nil), "mezo.ethereum_sidecar.v1.AssetsUnlockedEntriesRequest")
	proto.RegisterType((*AssetsUnlockedEntriesResponse)(nil), "mezo.ethereum_sidecar.v1.AssetsUnlockedEntriesResponse")
}

func init() {
	proto.RegisterFile("mezo/ethereum_sidecar/v1/ethereum_sidecar_bridge_out.proto", fileDescriptor_73e84e01faa13b80)
}

var fileDescriptor_73e84e01faa13b80 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x3f, 0x4b, 0xc3, 0x40,
	0x18, 0xc6, 0x73, 0x0a, 0x8a, 0x57, 0x75, 0x08, 0x16, 0x42, 0xb5, 0x69, 0xe9, 0xd4, 0xc5, 0x8b,
	0xad, 0xa0, 0xe2, 0xa4, 0xc5, 0x0e, 0xba, 0x08, 0x2d, 0x0e, 0xba, 0x84, 0x36, 0x79, 0x49, 0x43,
	0x4d, 0xae, 0xde, 0x7b, 0x09, 0xe8, 0x27, 0x70, 0xf4, 0x53, 0x38, 0xf9, 0x41, 0x3a, 0x76, 0x14,
	0x87, 0x22, 0xed, 0x17, 0x91, 0xe4, 0x9a, 0x82, 0x7f, 0x2a, 0xba, 0x3d, 0x5c, 0x9e, 0xdf, 0xf3,
	0xe6, 0x9e, 0x7b, 0xe9, 0x71, 0x00, 0x0f, 0xdc, 0x02, 0xd9, 0x03, 0x01, 0x51, 0x60, 0xa3, 0xef,
	0x82, 0xd3, 0x11, 0x56, 0x5c, 0xfb, 0x76, 0x66, 0x77, 0x85, 0xef, 0x7a, 0x60, 0xf3, 0x48, 0xb2,
	0x81, 0xe0, 0x92, 0xeb, 0x46, 0xc2, 0xb2, 0xaf, 0x3e, 0x16, 0xd7, 0x0a, 0x5b, 0x1e, 0xf7, 0x78,
	0x6a, 0xb2, 0x12, 0xa5, 0xfc, 0x85, 0xed, 0x74, 0x96, 0x8a, 0x49, 0x26, 0x28, 0xa5, 0x3e, 0x56,
	0x9e, 0x09, 0xdd, 0x39, 0x45, 0x04, 0x89, 0x57, 0xe1, 0x2d, 0x77, 0xfa, 0xe0, 0x36, 0x43, 0x29,
	0x7c, 0xc0, 0x16, 0xdc, 0x45, 0x80, 0x52, 0x3f, 0xa3, 0x9b, 0x98, 0xc8, 0xd0, 0x01, 0x1b, 0x65,
	0x47, 0x48, 0x83, 0x94, 0x49, 0x75, 0xad, 0x51, 0x1c, 0x8e, 0x4b, 0xda, 0xdb, 0xb8, 0x94, 0x77,
	0x38, 0x06, 0x1c, 0xd1, 0xed, 0x33, 0x9f, 0x5b, 0x41, 0x47, 0xf6, 0xd8, 0x79, 0x28, 0x5b, 0x1b,
	0x19, 0xd4, 0x4e, 0x18, 0xfd, 0x84, 0xae, 0xcf, 0x53, 0x20, 0x74, 0x8d, 0xa5, 0xbf, 0x64, 0xe4,
	0x32, 0xa4, 0x19, 0xba, 0x95, 0x6b, 0x5a, 0x5c, 0xf0, 0x9f, 0x38, 0xe0, 0x21, 0x82, 0x7e, 0x44,
	0x57, 0x41, 0x1d, 0x19, 0xa4, 0xbc, 0x5c, 0xcd, 0xd5, 0x4d, 0x96, 0x16, 0x35, 0xbb, 0x6e, 0x5c,
	0x63, 0x9f, 0xf9, 0x56, 0x66, 0xaf, 0xbf, 0x10, 0x5a, 0x6a, 0xce, 0xea, 0x6c, 0xab, 0x36, 0x1b,
	0x29, 0x74, 0x19, 0xc9, 0x36, 0x88, 0xd8, 0x77, 0x40, 0x7f, 0x24, 0x34, 0xff, 0xe3, 0x7c, 0xfd,
	0x80, 0x2d, 0x7a, 0x0f, 0xf6, 0x5b, 0xb1, 0x85, 0xc3, 0x7f, 0x73, 0xea, 0xa2, 0x8d, 0x8b, 0xe1,
	0xc4, 0x24, 0xa3, 0x89, 0x49, 0xde, 0x27, 0x26, 0x79, 0x9a, 0x9a, 0xda, 0x68, 0x6a, 0x6a, 0xaf,
	0x53, 0x53, 0xbb, 0xd9, 0xf3, 0x7c, 0xd9, 0x8b, 0xba, 0xcc, 0xe1, 0x81, 0x95, 0x84, 0xef, 0x72,
	0xe1, 0xa5, 0xc2, 0x9d, 0xaf, 0x95, 0x95, 0xad, 0x9a, 0xbc, 0x1f, 0x00, 0x76, 0x57, 0xd2, 0x2d,
	0xd8, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0x52, 0x9c, 0x0b, 0x76, 0x90, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EthereumSidecarBridgeOutServiceClient is the client API for EthereumSidecarBridgeOutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EthereumSidecarBridgeOutServiceClient interface {
	// AssetsUnlockedEntries returns AssetsUnlocked entries within a sequence
	// range.
	AssetsUnlockedEntries(ctx context.Context, in *AssetsUnlockedEntriesRequest, opts ...grpc.CallOption) (*AssetsUnlockedEntriesResponse, error)
}

type ethereumSidecarBridgeOutServiceClient struct {
	cc grpc1.ClientConn
}

func NewEthereumSidecarBridgeOutServiceClient(cc grpc1.ClientConn) EthereumSidecarBridgeOutServiceClient {
	return &ethereumSidecarBridgeOutServiceClient{cc}
}

func (c *ethereumSidecarBridgeOutServiceClient) AssetsUnlockedEntries(ctx context.Context, in *AssetsUnlockedEntriesRequest, opts ...grpc.CallOption) (*AssetsUnlockedEntriesResponse, error) {
	out := new(AssetsUnlockedEntriesResponse)
	err := c.cc.Invoke(ctx, "/mezo.ethereum_sidecar.v1.EthereumSidecarBridgeOutService/AssetsUnlockedEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EthereumSidecarBridgeOutServiceServer is the server API for EthereumSidecarBridgeOutService service.
type EthereumSidecarBridgeOutServiceServer interface {
	// AssetsUnlockedEntries returns AssetsUnlocked entries within a sequence
	// range.
	AssetsUnlockedEntries(context.Context, *AssetsUnlockedEntriesRequest) (*AssetsUnlockedEntriesResponse, error)
}

// UnimplementedEthereumSidecarBridgeOutServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEthereumSidecarBridgeOutServiceServer struct {
}

func (*UnimplementedEthereumSidecarBridgeOutServiceServer) AssetsUnlockedEntries(ctx context.Context, req *AssetsUnlockedEntriesRequest) (*AssetsUnlockedEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssetsUnlockedEntries not implemented")
}

func RegisterEthereumSidecarBridgeOutServiceServer(s grpc1.Server, srv EthereumSidecarBridgeOutServiceServer) {
	s.RegisterService(&_EthereumSidecarBridgeOutService_serviceDesc, srv)
}

func _EthereumSidecarBridgeOutService_AssetsUnlockedEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetsUnlockedEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthereumSidecarBridgeOutServiceServer).AssetsUnlockedEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mezo.ethereum_sidecar.v1.EthereumSidecarBridgeOutService/AssetsUnlockedEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthereumSidecarBridgeOutServiceServer).AssetsUnlockedEntries(ctx, req.(*AssetsUnlockedEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EthereumSidecarBridgeOutService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mezo.ethereum_sidecar.v1.EthereumSidecarBridgeOutService",
	HandlerType: (*EthereumSidecarBridgeOutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssetsUnlockedEntries",
			Handler:    _EthereumSidecarBridgeOutService_AssetsUnlockedEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mezo/ethereum_sidecar/v1/ethereum_sidecar_bridge_out.proto",
}

func (m *AssetsUnlockedEntriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetsUnlockedEntriesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetsUnlockedEntriesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SequenceEnd.Size()
		i -= size
		if _, err := m.SequenceEnd.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEthereumSidecarBridgeOut(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.SequenceStart.Size()
		i -= size
		if _, err := m.SequenceStart.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEthereumSidecarBridgeOut(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AssetsUnlockedEntriesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetsUnlockedEntriesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetsUnlockedEntriesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEthereumSidecarBridgeOut(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintEthereumSidecarBridgeOut(dAtA []byte, offset int, v uint64) int {
	offset -= sovEthereumSidecarBridgeOut(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AssetsUnlockedEntriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SequenceStart.Size()
	n += 1 + l + sovEthereumSidecarBridgeOut(uint64(l))
	l = m.SequenceEnd.Size()
	n += 1 + l + sovEthereumSidecarBridgeOut(uint64(l))
	return n
}

func (m *AssetsUnlockedEntriesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovEthereumSidecarBridgeOut(uint64(l))
		}
	}
	return n
}

func sovEthereumSidecarBridgeOut(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEthereumSidecarBridgeOut(x uint64) (n int) {
	return sovEthereumSidecarBridgeOut(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AssetsUnlockedEntriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthereumSidecarBridgeOut
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetsUnlockedEntriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetsUnlockedEntriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceStart", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumSidecarBridgeOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthereumSidecarBridgeOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumSidecarBridgeOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SequenceStart.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceEnd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumSidecarBridgeOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthereumSidecarBridgeOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumSidecarBridgeOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SequenceEnd.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEthereumSidecarBridgeOut(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEthereumSidecarBridgeOut
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AssetsUnlockedEntriesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthereumSidecarBridgeOut
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetsUnlockedEntriesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetsUnlockedEntriesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumSidecarBridgeOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumSidecarBridgeOut
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumSidecarBridgeOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &types.AssetsUnlocked{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEthereumSidecarBridgeOut(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEthereumSidecarBridgeOut
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEthereumSidecarBridgeOut(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEthereumSidecarBridgeOut
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthereumSidecarBridgeOut
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthereumSidecarBridgeOut
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEthereumSidecarBridgeOut
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEthereumSidecarBridgeOut
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEthereumSidecarBridgeOut
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEthereumSidecarBridgeOut        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEthereumSidecarBridgeOut          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEthereumSidecarBridgeOut = fmt.Errorf("proto: unexpected end of group")
)
