apiVersion: v1
kind: ConfigMap
metadata:
  name: contracts-exporter-config
  namespace: monitoring
data:
  addresses.txt: |
    testertesting:0x6e80164ea60673D64d5d6228beb684a1274Bb017
  contracts.txt: |
    PCV|0x4dDD70f4C603b6089c07875Be02fEdFD626b80Af|[{"inputs":[],"name":"debtToPay","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}]|debtToPay
