:toc: macro

= Local development

:icons: font
:numbered:
toc::[]

== Running the client locally

=== Single instance

To start a single client instance locally please use the `local_node.sh` script.
The script will compile the client, perform genesis, and start a local client
instance. 

=== Multiple client instances

There is a set of Make formulas allowing to set up multiple client instances
connected to each other locally. The formulas use Docker Compose to set up the
cluster so a Docker Desktop must be running locally.

To build the local network, use `make localnet-build` command. This command will
build and install `meso/node` image locally. 

The `make localnet-start` and `make localnet-stop` are used to start and stop
the four client instances. The client build takes some time and it is not
executed as a part of the `make localnet-start` command to save time. To rebuild
the client after changes in the code, you need to use `make localnet-build`. 

To see the logs of four client instances, please use `make localnet-show-logstream`.

The configuration for the four nodes is available in the `build` directory.

When `make localnet-start` is used for the first time, a configuration for the
four nodes is generated. To clear the chain state and reset the configuration,
use `make localnet-clean` followed by `make localnet-start`.