apiVersion: v1
kind: ConfigMap
metadata:
  name: balance-exporter-config
  namespace: monitoring
data:
  addresses-mezo.txt: |
    testertesting:0x6e80164ea60673D64d5d6228beb684a1274Bb017
  addresses-ethereum.txt: |
    bridge-reimbursement-pool:0xF6A9d3B42615ACcc70A4e60b389c851C8FB1524d
    bridge-worker:0x419b505186fe3880Ac6407AcD14dD0398d6e8Ec8
