package testbed

// EvmByteCode is the EVM bytecode of the BTC token precompile. This code is
// returned by eth_getCode and ensures the precompile address is detected as a
// smart contract by external services. Note: It should NOT contain a 0x prefix
//
// WARNING! This value is used in the InitChain ABCI hook and affects the app state hash.
// Remember to always update this constant upon changes in the precompile ABI.
// However, note that any changes made to this value are immediately effective only for
// new chains (e.g. localnet). For live chains, this constant serves as a reference
// but, the actual update must be done through the `setPrecompileByteCode` method
// provided by the `Maintenance` precompile.
//
// This bytecode was generated by compiling the BTCCaller contract
// found in the precompile/hardhat package. Then extracting `deployedBytecode`
// from the build artifacts
const EvmByteCode = ""
